In [1]:
import torch

Get Patches from an image given the patch indices. 

Patches are non-overlapping

Case A: 2D images

In [102]:
x = torch.arange(64).reshape(8,8)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])

In [105]:
#break image into 4x4 patches
patch_size = 4
x.unfold(0,patch_size,patch_size).unfold(1,patch_size,patch_size)

tensor([[[[ 0,  1,  2,  3],
          [ 8,  9, 10, 11],
          [16, 17, 18, 19],
          [24, 25, 26, 27]],

         [[ 4,  5,  6,  7],
          [12, 13, 14, 15],
          [20, 21, 22, 23],
          [28, 29, 30, 31]]],


        [[[32, 33, 34, 35],
          [40, 41, 42, 43],
          [48, 49, 50, 51],
          [56, 57, 58, 59]],

         [[36, 37, 38, 39],
          [44, 45, 46, 47],
          [52, 53, 54, 55],
          [60, 61, 62, 63]]]])

In [ ]:
patch_idx_h = torch.tensor([0,1])
patch_idx_w = torch.tensor([0,1])

In [150]:
def get_patches_2D(x:torch.Tensor, patch_idxs:tuple[torch.Tensor], patch_size:int):
    '''Get Patches from an HxW image given the patch indices. 
    Todo: extend it to 3D
    '''
    #x shape = (h, w)
    assert len(x.shape) == 2
    print('image x' , x)
    patch_idx_h, patch_idx_w = patch_idxs
    assert len(patch_idx_h) == len(patch_idx_w)
    print('patch_idx_h, patch_idx_w', patch_idx_h, patch_idx_w)
    print('Num patches = ', len(patch_idx_h))

    #get the h indices of the patches: convert h indices to desired output shape: (num_patches, patch_size, patch_size)
    start_idx_h = patch_idx_h*patch_size
    print('start_idx_h', start_idx_h)
    idxs_h = start_idx_h.repeat(patch_size,1) + torch.arange(patch_size)[:,None]
    print('patch idxs_h', idxs_h)
    idxs_h = torch.repeat_interleave(idxs_h, patch_size, dim=1)
    print('idxs_h repeated for same patch', idxs_h)
    idxs_h = idxs_h.unfold(0,patch_size, patch_size).unfold(1,patch_size, patch_size).squeeze(dim=0)
    print('idxs_h', idxs_h)
    print('idxs_h.shape', idxs_h.shape)

    print('\n')

    #get the w indices of the patches: convert h indices to desired output shape: (num_patches, patch_size, patch_size)
    start_idx_w = patch_idx_w*patch_size
    print('start_idx_w', start_idx_w)
    idxs_w = torch.transpose(start_idx_w.repeat(patch_size,1)+torch.arange(patch_size)[:,None], 0, 1)
    print('patch idxs_w', idxs_w)
    idxs_w = torch.repeat_interleave(idxs_w, patch_size, dim=0)
    print('idxs_w repeated for same patch', idxs_w)
    idxs_w = idxs_w.unfold(0, patch_size, patch_size).unfold(1,patch_size, patch_size).squeeze(dim=1)
    print('idxs_w', idxs_w)
    print('idxs_w.shape', idxs_w.shape)
    
    patches = x[idxs_h,idxs_w]
    print('Selected patches = ', patches)
    print('Selected patches shape = ', patches.shape)
    return patches


patch_idx_h = torch.tensor([0,3,1])
patch_idx_w = torch.tensor([0,2,3])
patch_idxs = (patch_idx_h, patch_idx_w)
patch_size = 2
selected_patches = get_patches_2D(x,patch_idxs, patch_size)



image x tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29, 30, 31],
        [32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47],
        [48, 49, 50, 51, 52, 53, 54, 55],
        [56, 57, 58, 59, 60, 61, 62, 63]])
patch_idx_h, patch_idx_w tensor([0, 3, 1]) tensor([0, 2, 3])
Num patches =  3
start_idx_h tensor([0, 6, 2])
patch idxs_h tensor([[0, 6, 2],
        [1, 7, 3]])
idxs_h repeated for same patch tensor([[0, 0, 6, 6, 2, 2],
        [1, 1, 7, 7, 3, 3]])
idxs_h tensor([[[0, 0],
         [1, 1]],

        [[6, 6],
         [7, 7]],

        [[2, 2],
         [3, 3]]])
idxs_h.shape torch.Size([3, 2, 2])


start_idx_w tensor([0, 4, 6])
patch idxs_w tensor([[0, 1],
        [4, 5],
        [6, 7]])
idxs_w repeated for same patch tensor([[0, 1],
        [0, 1],
        [4, 5],
        [4, 5],
        [6, 7],
        [6, 7]])
idxs_w tensor([[[0, 1],
         [0

In [158]:
torch.pi

3.141592653589793

In [130]:
def ravel_index_(index, shape):
    """Ravel multi-dimensional indices to 1D index
    similar to np.ravel_multi_index
    Args:
        index (torch.tensor): indices in reversed order dn, ..., d1, with shape (..., n)
        shape (tuple): dn, ..., d1
    """
    #index = torch.tensor(index, dtype=torch.int64)
    shape = torch.tensor((1,) + shape[::-1], dtype=torch.int64) # =(1, d1, d1*d2, ..., d1*...*dn)
    shape = torch.cumprod(shape, dim=0)[:-1].flip(0) # =(d1*...*dn-1, ..., d1*d2, d1, 1)
    index = (index * shape).sum(dim=-1) # (...,)
    return index

In [138]:
patches = (x.unfold(0,patch_size,patch_size).unfold(1,patch_size,patch_size)).contiguous().view(-1,2,2)
patches.shape

torch.Size([16, 2, 2])

In [139]:
patches

tensor([[[ 0,  1],
         [ 8,  9]],

        [[ 2,  3],
         [10, 11]],

        [[ 4,  5],
         [12, 13]],

        [[ 6,  7],
         [14, 15]],

        [[16, 17],
         [24, 25]],

        [[18, 19],
         [26, 27]],

        [[20, 21],
         [28, 29]],

        [[22, 23],
         [30, 31]],

        [[32, 33],
         [40, 41]],

        [[34, 35],
         [42, 43]],

        [[36, 37],
         [44, 45]],

        [[38, 39],
         [46, 47]],

        [[48, 49],
         [56, 57]],

        [[50, 51],
         [58, 59]],

        [[52, 53],
         [60, 61]],

        [[54, 55],
         [62, 63]]])

In [140]:
patch_idxs_T = torch.stack(patch_idxs,dim=0).T
flat_patch_idxs = ravel_index_(patch_idxs_T,(x.shape[0]//patch_size,x.shape[1]//patch_size))
flat_patch_idxs

tensor([ 0, 14,  7])

In [141]:
patches[flat_patch_idxs]

tensor([[[ 0,  1],
         [ 8,  9]],

        [[52, 53],
         [60, 61]],

        [[22, 23],
         [30, 31]]])

In [162]:
selected_patches

tensor([[[ 0,  1],
         [ 8,  9]],

        [[52, 53],
         [60, 61]],

        [[22, 23],
         [30, 31]]])

In [164]:
mul = torch.tensor([1,2,3])[:,None,None]
selected_patches*mul

tensor([[[  0,   1],
         [  8,   9]],

        [[104, 106],
         [120, 122]],

        [[ 66,  69],
         [ 90,  93]]])

In [166]:
torch.arange(64).reshape(8,8).sum()

tensor(2016)

In [11]:
patches = torch.arange(32).reshape(2,1,4,4)
patches

tensor([[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11],
          [12, 13, 14, 15]]],


        [[[16, 17, 18, 19],
          [20, 21, 22, 23],
          [24, 25, 26, 27],
          [28, 29, 30, 31]]]])

In [16]:
img = patches.view(2,1,4,1,4,1).expand(2,1,4,3,4,3).contiguous().view(2,1,12,12)
img

tensor([[[[ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3],
          [ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3],
          [ 0,  0,  0,  1,  1,  1,  2,  2,  2,  3,  3,  3],
          [ 4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7],
          [ 4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7],
          [ 4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7],
          [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
          [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
          [ 8,  8,  8,  9,  9,  9, 10, 10, 10, 11, 11, 11],
          [12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15],
          [12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15],
          [12, 12, 12, 13, 13, 13, 14, 14, 14, 15, 15, 15]]],


        [[[16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19],
          [16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19],
          [16, 16, 16, 17, 17, 17, 18, 18, 18, 19, 19, 19],
          [20, 20, 20, 21, 21, 21, 22, 22, 22, 23, 23, 23],
          [20, 20, 20, 21, 21, 21, 2

In [21]:
img_patches = img.view(2,1,4,3,4,3).permute(0,2,4,1,3,5).contiguous().view(-1,1,3,3)
img_patches

tensor([[[[ 0,  0,  0],
          [ 0,  0,  0],
          [ 0,  0,  0]]],


        [[[ 1,  1,  1],
          [ 1,  1,  1],
          [ 1,  1,  1]]],


        [[[ 2,  2,  2],
          [ 2,  2,  2],
          [ 2,  2,  2]]],


        [[[ 3,  3,  3],
          [ 3,  3,  3],
          [ 3,  3,  3]]],


        [[[ 4,  4,  4],
          [ 4,  4,  4],
          [ 4,  4,  4]]],


        [[[ 5,  5,  5],
          [ 5,  5,  5],
          [ 5,  5,  5]]],


        [[[ 6,  6,  6],
          [ 6,  6,  6],
          [ 6,  6,  6]]],


        [[[ 7,  7,  7],
          [ 7,  7,  7],
          [ 7,  7,  7]]],


        [[[ 8,  8,  8],
          [ 8,  8,  8],
          [ 8,  8,  8]]],


        [[[ 9,  9,  9],
          [ 9,  9,  9],
          [ 9,  9,  9]]],


        [[[10, 10, 10],
          [10, 10, 10],
          [10, 10, 10]]],


        [[[11, 11, 11],
          [11, 11, 11],
          [11, 11, 11]]],


        [[[12, 12, 12],
          [12, 12, 12],
          [12, 12, 12]]],


        [[[1

In [17]:
patch_idxs = torch.nonzero((patches == 5) | (patches == 30), as_tuple=True)
patch_idxs

(tensor([0, 1]), tensor([0, 0]), tensor([1, 3]), tensor([1, 2]))

In [10]:
def ravel_tuple_index(index:tuple[torch.Tensor], shape:tuple[int]):
    """Ravel multi-dimensional indices to 1D index
    similar to np.ravel_multi_index
    Args:
        index (torch.tensor): indices in reversed order dn, ..., d1, with shape (..., n)
        shape (tuple): dn, ..., d1
    """
    index = torch.stack(index,dim=0).T
    #index = torch.tensor(index, dtype=torch.int64)
    shape = torch.tensor((1,) + shape[::-1], dtype=torch.int64) # =(1, d1, d1*d2, ..., d1*...*dn)
    shape = torch.cumprod(shape, dim=0)[:-1].flip(0) # =(d1*...*dn-1, ..., d1*d2, d1, 1)
    index = (index * shape).sum(dim=-1) # (...,)
    return index

In [24]:
img_patches[ravel_tuple_index(patch_idxs, patches.shape)]

tensor([[[[ 5,  5,  5],
          [ 5,  5,  5],
          [ 5,  5,  5]]],


        [[[30, 30, 30],
          [30, 30, 30],
          [30, 30, 30]]]])

In [156]:
ravel_tuple_index()

tensor([2, 6, 7])

In [157]:
a

{'x1': tensor([2, 6, 7])}