In [4]:
class A():
    def __init__(self):
        pass
    def a(self,x):
        if x == 'm':
            print('m')
        elif x == 'n':
            print('n')

class B(A):
    def __init__(self):
        super().__init__()
    def a(self,x):
        if x == 'm'
        super().a(x)
        if x == 'n':
            print('k')

b = B()
b.a('n')

n
k


In [1]:
import numpy as np

In [10]:
arr = np.random.randn(3,5)
pad_width = [(2, 3), (1, 2)]  # Padding for (w, h, d)
arr1 = np.pad(arr, pad_width, mode='constant', constant_values=0)

In [11]:
arr

array([[-1.0363135 ,  0.13769319,  1.55459688,  0.75076252, -1.5963932 ],
       [-0.24597258, -0.30131506,  0.48089561, -0.14366398,  2.15835096],
       [ 0.06115847, -0.76221813, -0.68150188,  0.16991158,  0.73216926]])

In [22]:
arr1


array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -1.0363135 ,  0.13769319,  1.55459688,  0.75076252,
        -1.5963932 ,  0.        ,  0.        ],
       [ 0.        , -0.24597258, -0.30131506,  0.48089561, -0.14366398,
         2.15835096,  0.        ,  0.        ],
       [ 0.        ,  0.06115847, -0.76221813, -0.68150188,  0.16991158,
         0.73216926,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [27]:
arr1=torch.from_numpy(arr1)

In [31]:
arr1

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.0363,  1.0000,  1.0000,  1.0000, -1.5964,  0.0000,  0.0000],
        [ 0.0000, -0.2460, -0.3013,  1.0000, -0.1437,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000, -0.7622, -0.6815,  1.0000,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [36]:
a=torch.randn(4,4)

In [37]:
a

tensor([[ 1.5927,  0.8941, -0.5614, -0.1146],
        [ 1.4755, -0.7206, -0.9578, -0.1435],
        [ 1.0759, -0.8149,  0.6676,  1.3719],
        [ 0.0792,  0.0536, -0.4410, -1.5718]])

In [38]:
torch.clamp(a,0,1)

tensor([[1.0000, 0.8941, 0.0000, 0.0000],
        [1.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 0.0000, 0.6676, 1.0000],
        [0.0792, 0.0536, 0.0000, 0.0000]])

In [34]:
v=''
f"dd{v}"

'dd'

In [28]:
arr1[arr1>0] = 1

In [29]:
arr1

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.0363,  1.0000,  1.0000,  1.0000, -1.5964,  0.0000,  0.0000],
        [ 0.0000, -0.2460, -0.3013,  1.0000, -0.1437,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000, -0.7622, -0.6815,  1.0000,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

## Sliding Windows

In [ ]:
def sliding_windows()

In [23]:
import torch

In [18]:
arr = torch.randn(5,5)
arr

tensor([[-0.0322,  0.0130,  0.3563,  1.1467,  0.0661],
        [-0.2312,  0.0656,  0.0694,  1.1842,  1.7015],
        [ 0.1408, -0.8996, -0.0693, -1.1149, -1.1485],
        [ 1.0666, -1.0215, -0.2648, -1.3125,  1.1425],
        [-0.0881,  0.2391,  0.1623, -0.5130, -0.5677]])

In [19]:
w, h = arr.shape
n = 2
s = 1
# Calculate the shape of the output windows
out_w = (w - n) // s + 1
out_h = (h - n) // s + 1

# Unfold the dimensions and reshape
windows = arr.unfold(0, n, s).unfold(1, n, s)
windows = windows.contiguous().view(out_w, out_h, n, n)

In [21]:
windows.reshape(16,2,2)

tensor([[[-0.0322,  0.0130],
         [-0.2312,  0.0656]],

        [[ 0.0130,  0.3563],
         [ 0.0656,  0.0694]],

        [[ 0.3563,  1.1467],
         [ 0.0694,  1.1842]],

        [[ 1.1467,  0.0661],
         [ 1.1842,  1.7015]],

        [[-0.2312,  0.0656],
         [ 0.1408, -0.8996]],

        [[ 0.0656,  0.0694],
         [-0.8996, -0.0693]],

        [[ 0.0694,  1.1842],
         [-0.0693, -1.1149]],

        [[ 1.1842,  1.7015],
         [-1.1149, -1.1485]],

        [[ 0.1408, -0.8996],
         [ 1.0666, -1.0215]],

        [[-0.8996, -0.0693],
         [-1.0215, -0.2648]],

        [[-0.0693, -1.1149],
         [-0.2648, -1.3125]],

        [[-1.1149, -1.1485],
         [-1.3125,  1.1425]],

        [[ 1.0666, -1.0215],
         [-0.0881,  0.2391]],

        [[-1.0215, -0.2648],
         [ 0.2391,  0.1623]],

        [[-0.2648, -1.3125],
         [ 0.1623, -0.5130]],

        [[-1.3125,  1.1425],
         [-0.5130, -0.5677]]])