In [4]:
class A():
    def __init__(self):
        pass
    def a(self,x):
        if x == 'm':
            print('m')
        elif x == 'n':
            print('n')

class B(A):
    def __init__(self):
        super().__init__()
    def a(self,x):
        if x == 'm'
        super().a(x)
        if x == 'n':
            print('k')

b = B()
b.a('n')

n
k


In [1]:
import numpy as np

In [10]:
arr = np.random.randn(3,5)
pad_width = [(2, 3), (1, 2)]  # Padding for (w, h, d)
arr1 = np.pad(arr, pad_width, mode='constant', constant_values=0)

In [11]:
arr

array([[-1.0363135 ,  0.13769319,  1.55459688,  0.75076252, -1.5963932 ],
       [-0.24597258, -0.30131506,  0.48089561, -0.14366398,  2.15835096],
       [ 0.06115847, -0.76221813, -0.68150188,  0.16991158,  0.73216926]])

In [22]:
arr1


array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        , -1.0363135 ,  0.13769319,  1.55459688,  0.75076252,
        -1.5963932 ,  0.        ,  0.        ],
       [ 0.        , -0.24597258, -0.30131506,  0.48089561, -0.14366398,
         2.15835096,  0.        ,  0.        ],
       [ 0.        ,  0.06115847, -0.76221813, -0.68150188,  0.16991158,
         0.73216926,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ]])

In [27]:
arr1=torch.from_numpy(arr1)

In [31]:
arr1

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.0363,  1.0000,  1.0000,  1.0000, -1.5964,  0.0000,  0.0000],
        [ 0.0000, -0.2460, -0.3013,  1.0000, -0.1437,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000, -0.7622, -0.6815,  1.0000,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

In [36]:
a=torch.randn(4,4)

In [37]:
a

tensor([[ 1.5927,  0.8941, -0.5614, -0.1146],
        [ 1.4755, -0.7206, -0.9578, -0.1435],
        [ 1.0759, -0.8149,  0.6676,  1.3719],
        [ 0.0792,  0.0536, -0.4410, -1.5718]])

In [38]:
torch.clamp(a,0,1)

tensor([[1.0000, 0.8941, 0.0000, 0.0000],
        [1.0000, 0.0000, 0.0000, 0.0000],
        [1.0000, 0.0000, 0.6676, 1.0000],
        [0.0792, 0.0536, 0.0000, 0.0000]])

In [34]:
v=''
f"dd{v}"

'dd'

In [28]:
arr1[arr1>0] = 1

In [29]:
arr1

tensor([[ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000, -1.0363,  1.0000,  1.0000,  1.0000, -1.5964,  0.0000,  0.0000],
        [ 0.0000, -0.2460, -0.3013,  1.0000, -0.1437,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  1.0000, -0.7622, -0.6815,  1.0000,  1.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000]],
       dtype=torch.float64)

## Sliding Windows

In [ ]:
def sliding_windows()

In [23]:
import torch

In [18]:
arr = torch.randn(5,5)
arr

tensor([[-0.0322,  0.0130,  0.3563,  1.1467,  0.0661],
        [-0.2312,  0.0656,  0.0694,  1.1842,  1.7015],
        [ 0.1408, -0.8996, -0.0693, -1.1149, -1.1485],
        [ 1.0666, -1.0215, -0.2648, -1.3125,  1.1425],
        [-0.0881,  0.2391,  0.1623, -0.5130, -0.5677]])

In [19]:
w, h = arr.shape
n = 2
s = 1
# Calculate the shape of the output windows
out_w = (w - n) // s + 1
out_h = (h - n) // s + 1

# Unfold the dimensions and reshape
windows = arr.unfold(0, n, s).unfold(1, n, s)
windows = windows.contiguous().view(out_w, out_h, n, n)

In [21]:
windows.reshape(16,2,2)

tensor([[[-0.0322,  0.0130],
         [-0.2312,  0.0656]],

        [[ 0.0130,  0.3563],
         [ 0.0656,  0.0694]],

        [[ 0.3563,  1.1467],
         [ 0.0694,  1.1842]],

        [[ 1.1467,  0.0661],
         [ 1.1842,  1.7015]],

        [[-0.2312,  0.0656],
         [ 0.1408, -0.8996]],

        [[ 0.0656,  0.0694],
         [-0.8996, -0.0693]],

        [[ 0.0694,  1.1842],
         [-0.0693, -1.1149]],

        [[ 1.1842,  1.7015],
         [-1.1149, -1.1485]],

        [[ 0.1408, -0.8996],
         [ 1.0666, -1.0215]],

        [[-0.8996, -0.0693],
         [-1.0215, -0.2648]],

        [[-0.0693, -1.1149],
         [-0.2648, -1.3125]],

        [[-1.1149, -1.1485],
         [-1.3125,  1.1425]],

        [[ 1.0666, -1.0215],
         [-0.0881,  0.2391]],

        [[-1.0215, -0.2648],
         [ 0.2391,  0.1623]],

        [[-0.2648, -1.3125],
         [ 0.1623, -0.5130]],

        [[-1.3125,  1.1425],
         [-0.5130, -0.5677]]])

In [1]:
# Example usage
B = 2    # Batch size
C = 3  # Number of channels in output mask
W = 128   # Width of the input image
H = 128   # Height of the input image
D = 128   # Depth of the input image
P = 32   # Patch size
W_P, H_P, D_P = W // P, H // P, D // P  # Number of patches

In [3]:
import torch

In [28]:
label_map = torch.randint(0, 2, (B, 1, W_P, H_P, D_P)).float()  # Random label map
patch_preds = torch.rand((B, C, W_P, H_P, D_P, P, P, P)) 

In [29]:
patch_preds1 = patch_preds.view(B*W_P*H_P*D_P, C, P, P, P)

In [30]:
label_map = label_map.view(B*W_P*H_P*D_P,1,1,1,1)
label_map = label_map.expand(-1, C, P, P, P)

In [31]:
label_map.shape


torch.Size([128, 3, 32, 32, 32])

In [32]:
# Zero out the patch predictions where the mask is 0
final_patch_preds = patch_preds1 * label_map  # Broadcasting to apply the mask

# Reshape to get the final mask of shape (B, C', W, H, D)
final_mask1 = final_patch_preds.view(B, C, W_P * P, H_P * P, D_P * P)

In [37]:
final_mask1.shape

torch.Size([2, 3, 128, 128, 128])

In [25]:
(final_mask1==final_mask).sum()


tensor(7012352)

In [27]:
import numpy as np
np.prod(final_mask1.shape)

12582912

In [18]:
patch_preds1.shape

torch.Size([128, 3, 32, 32, 32])

In [14]:
label_map_expanded = label_map.view(B, 1, W_P, H_P, D_P, 1, 1, 1)
mask = label_map_expanded.expand(-1, C, -1, -1, -1, P, P, P)  # (B, C', W/P, H/P, D/P, P, P, P)
mask.shape

torch.Size([2, 3, 4, 4, 4, 32, 32, 32])

In [38]:
label_map_expanded = label_map.view(B, 1, W_P, H_P, D_P, 1, 1, 1)
mask = label_map_expanded.expand(-1, C, -1, -1, -1, P, P, P)  # (B, C', W/P, H/P, D/P, P, P, P)

# Zero out the patch predictions where the mask is 0
final_patch_preds = patch_preds.view(B, C, W_P, H_P, D_P, P, P, P) * mask  # Broadcasting to apply the mask

# Reshape to get the final mask of shape (B, C', W, H, D)
final_mask = final_patch_preds.view(B, C, W_P * P, H_P * P, D_P * P)



RuntimeError: shape '[2, 1, 4, 4, 4, 1, 1, 1]' is invalid for input of size 12582912

In [16]:
final_mask.shape

torch.Size([2, 3, 128, 128, 128])

In [3]:
import torch

In [39]:
# Initialize parameters
B = 2  # Batch size
C = 4  # Number of channels in the image
W, H, D = 128, 128, 128  # Dimensions of the image
P = 32  # Patch size
C_prime = 3 # Number of channels in the output mask

In [7]:
patch_pred_labels = torch.randint(0, 2, (B, 1, W // P, H // P, D // P))  # Random patch predictions
patch_pred_labels.shape


torch.Size([2, 1, 4, 4, 4])

In [8]:
patch_embeddings = torch.randn(B, 512, W // P, H // P, D // P)
patch_embeddings.shape

torch.Size([2, 512, 4, 4, 4])

In [21]:
pos_indices = patch_pred_labels.nonzero(as_tuple=True)
patch_embeddings[pos_indices].shape

torch.Size([73])

In [25]:
indices

(tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
         1]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,
         3, 3, 3, 3, 3, 3, 3, 3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
         1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
         3]),
 tensor([0, 0, 1, 1, 1, 2, 2, 3, 3, 0, 0, 0, 1, 2, 2, 0, 0, 0, 1, 2, 2, 2, 3, 3,
         0, 0, 0, 1, 1, 2, 2, 3, 3, 0, 1, 2, 2, 2, 3, 3, 3, 3, 0, 0, 0, 1, 1, 2,
         2, 3, 3, 3, 0, 1, 1, 1, 2, 2, 2, 2, 3, 3, 0, 1, 1, 1, 2, 2

In [43]:
# Extract indices where patch_pred_labels is True
indices = patch_pred_labels.nonzero(as_tuple=True)

# Use the indices to gather the embeddings
# We need to gather over the first dimension (batch)
patch_embeddings_extracted = patch_embeddings[indices[0], :, indices[2], indices[3], indices[4]]
patch_embeddings_extracted = patch_embeddings_extracted.view(73,1,8,8,8)
print(patch_embeddings_extracted.shape)

# Reshape to (K, 512)
#patch_embeddings_extracted = patch_embeddings_extracted.view(-1, 512)

torch.Size([73, 1, 8, 8, 8])


In [44]:
# Define a simple network B for mask prediction
class Net(torch.nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.up = torch.nn.Upsample(scale_factor=4, mode='nearest')
        self.conv = torch.nn.Conv3d(1, 3, kernel_size=3, padding=1)

    def forward(self, x):
        return self.conv(self.up(x))
net = Net()

In [45]:
patch_embeddings_extracted = net(patch_embeddings_extracted)

In [46]:
patch_embeddings_extracted.shape

torch.Size([73, 3, 32, 32, 32])

In [63]:
predicted_mask = torch.zeros((B, 3, W, H, D))
predicted_mask.dtype

torch.float32

In [62]:
patch_embeddings_extracted

tensor([[[[[-2.6534e-02, -4.2508e-02, -4.2508e-02,  ..., -3.8891e-02,
            -3.8891e-02, -5.7925e-02],
           [ 3.1087e-02,  2.2982e-02,  2.2982e-02,  ...,  1.2055e-02,
             1.2055e-02, -3.0848e-02],
           [ 3.1087e-02,  2.2982e-02,  2.2982e-02,  ...,  1.2055e-02,
             1.2055e-02, -3.0848e-02],
           ...,
           [-3.5975e-01, -3.1258e-01, -3.1258e-01,  ...,  3.0900e-01,
             3.0900e-01, -6.6735e-02],
           [-3.5975e-01, -3.1258e-01, -3.1258e-01,  ...,  3.0900e-01,
             3.0900e-01, -6.6735e-02],
           [-3.0445e-01, -2.4495e-01, -2.4495e-01,  ...,  2.2984e-01,
             2.2984e-01, -1.7113e-01]],

          [[-3.1042e-02, -2.7701e-02, -2.7701e-02,  ..., -2.7373e-02,
            -2.7373e-02, -4.1076e-02],
           [ 1.1248e-02,  2.5189e-02,  2.5189e-02,  ...,  1.3773e-02,
             1.3773e-02, -2.6182e-02],
           [ 1.1248e-02,  2.5189e-02,  2.5189e-02,  ...,  1.3773e-02,
             1.3773e-02, -2.6182e-02],
 

In [77]:
fill_indices = torch.nonzero(patch_pred_labels, as_tuple=False)
full_predicted_mask = torch.zeros((B, 3, W, H, D))




RuntimeError: shape mismatch: value tensor of shape [73, 3, 32, 32, 32] cannot be broadcast to indexing result of shape [73, 32, 3]

In [ ]:
# Iterate over fill_indices and scatter the predicted masks into the full tensor
for i in range(fill_indices.size(0)):
    b, _, w_idx, h_idx, d_idx = fill_indices[i]
    full_predicted_mask[b, :, w_idx * P:(w_idx + 1) * P,
                         h_idx * P:(h_idx + 1) * P,
                         d_idx * P:(d_idx + 1) * P] = patch_embeddings_extracted[i]

In [71]:
full_predicted_mask.shape

torch.Size([2, 3, 128, 128, 128])

In [67]:
indices[0]
indices = (torch.tensor(indices[i],dtype=torch.long) for i in range(len(indices)))

In [69]:
indices[0]

TypeError: 'generator' object is not subscriptable

In [68]:
predicted_mask[indices[0] :, indices[2] * P: (indices[2] + 1) * P, indices[3] * P: (indices[3] + 1) * P, indices[4] * P: (indices[4] + 1) * P] = patch_embeddings_extracted

TypeError: 'generator' object is not subscriptable

In [61]:
(indices[4] + 1)*P

tensor([ 64, 128,  32,  64,  96,  64, 128,  64, 128,  32,  96, 128, 128,  32,
        128,  64,  96, 128,  96,  32,  96, 128,  96, 128,  32,  96, 128,  64,
        128,  64,  96,  96, 128,  96, 128,  64,  96, 128,  32,  64,  96, 128,
         64,  96, 128,  32,  96,  32,  64,  32,  64,  96,  32,  64,  96, 128,
         32,  64,  96, 128,  64, 128, 128,  32,  64, 128,  32,  64, 128,  32,
         64,  96, 128])

In [54]:
indices[0].dtype

torch.int64

In [24]:
patch_embeddings[indices[0], :, indices[2], indices[3], indices[4]].shape

torch.Size([73, 512])

In [17]:
patch_embeddings_extracted.shape

torch.Size([73, 512])

In [2]:
import torch

In [14]:
a = torch.randn(2,27,4,4,4)

In [17]:
a.permute(0,2,3,4,1).contiguous().view(-1,3,3,3).unsqueeze(1).shape

torch.Size([128, 1, 3, 3, 3])

In [28]:
a = torch.randn(1,3,2,3,2)
a

tensor([[[[[-1.2816,  0.3369],
           [-0.9877, -0.4192],
           [ 0.6433, -0.2720]],

          [[ 0.3197, -0.8071],
           [ 0.4907, -0.3945],
           [-1.2484, -1.2634]]],


         [[[ 0.7450, -1.9769],
           [-0.5431, -0.4924],
           [-1.6434, -1.0368]],

          [[-0.2818,  0.3876],
           [ 2.8121, -0.6389],
           [ 0.2694,  0.2201]]],


         [[[-0.0977, -1.5234],
           [-1.1313,  0.2077],
           [-0.0113, -0.5947]],

          [[-0.0258, -1.5154],
           [ 0.5600,  1.5473],
           [-0.3395, -0.3595]]]]])

In [35]:
b = torch.randint(2,(1,1,2,3,2))
b

tensor([[[[[1, 1],
           [1, 0],
           [1, 1]],

          [[0, 1],
           [1, 1],
           [0, 0]]]]])

In [36]:
idxs = b.nonzero(as_tuple=True)

In [37]:
idxs

(tensor([0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([0, 0, 0, 0, 0, 0, 0, 0]),
 tensor([0, 0, 0, 0, 0, 1, 1, 1]),
 tensor([0, 0, 1, 2, 2, 0, 1, 1]),
 tensor([0, 1, 0, 0, 1, 1, 0, 1]))

In [40]:
a[idxs[0],:,idxs[2],idxs[3],idxs[4]].shape

torch.Size([8, 3])

In [41]:
a.shape

torch.Size([1, 3, 2, 3, 2])

In [43]:
c = torch.randn(18,27)

In [44]:
torch.equal(c.view(18, 1, 3, 3, 3),c.view(18, 3, 3, 3).unsqueeze(1))

True

In [13]:
import csv

def print_metrics_table(csv_filename):
    # Read the csv file
    with open(csv_filename, mode='r') as file:
        reader = csv.DictReader(file)
        # Get the first row (data) from the CSV
        data = next(reader)

    # Filter out 'epoch' and 'step' columns
    metrics = {k: v for k, v in data.items() if k not in ['epoch', 'step']}

    # Create the header for the table
    table = "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n"
    table += "┃        Test metric        ┃       DataLoader 0        ┃\n"
    table += "┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n"

    # Dynamically create rows based on the remaining columns (metrics)
    for metric, value in metrics.items():
        table += f"│ {metric:<23}   │    {value:<23}│\n"

    # Create the footer for the table
    table += "└───────────────────────────┴───────────────────────────┘"

    # Print the formatted table
    print(table)

# Example usage
print_metrics_table('/home/sanyal/Projects/BraTS3DDiff/logs/bratseg_logs/diffusion/BraTS23-DiffUNet-roi_96-meantype_xstart-with_deno_loss-no_mse_loss/test/runs/2024-08-22_19-39-32/csv/version_0/metrics.csv')


┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃        Test metric        ┃       DataLoader 0        ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ test/bce_loss             │    0.612697958946228      │
│ test/dice                 │    0.8849524259567261     │
│ test/dice_ET              │    0.8522501587867737     │
│ test/dice_TC              │    0.8944156765937805     │
│ test/dice_WT              │    0.9081919193267822     │
│ test/dice_loss            │    0.9753769636154175     │
│ test/loss                 │    1.7974729537963867     │
│ test/mse_loss             │    0.20939810574054718    │
└───────────────────────────┴───────────────────────────┘


In [7]:
import pandas as pd
pd.read_csv('/home/sanyal/Projects/BraTS3DDiff/logs/bratseg_logs/diffusion/BraTS23-DiffUNet-roi_96-meantype_xstart-with_deno_loss-no_mse_loss/test/runs/2024-08-22_19-39-32/csv/version_0/metrics.csv').T

0
epoch           0.000000
step            0.000000
test/bce_loss   0.612698
test/dice       0.884952
test/dice_ET    0.852250
test/dice_TC    0.894416
test/dice_WT    0.908192
test/dice_loss  0.975377
test/loss       1.797473
test/mse_loss   0.209398